# Generated by Django 5.2.1 on 2025-08-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='balance_after_transactions',
            new_name='balance_after_transaction',
        ),
    ]
