# Generated by Django 5.2.1 on 2025-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_balance_after_transactions_transactionmodel_balance_after_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan paid'), (5, 'Transfer')], null=True),
        ),
    ]
